# Generated by Django 2.0.6 on 2018-06-19 14:54

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Procedure',
                'verbose_name_plural': 'Procedures',
            },
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, validators=[api.models.validate_date])),
                ('initial_time', models.TimeField(default=django.utils.timezone.now)),
                ('final_time', models.TimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Patient')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Procedure')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Schedules',
                'ordering': ['date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='scheduling',
            unique_together={('date', 'procedure', 'patient')},
        ),
    ]
